# URL de conexión al contenedor 'db'
spring.datasource.url=jdbc:mysql://db:3306/db_colegio?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

# Credenciales (son las mismas para ambos)
spring.datasource.username=root
spring.datasource.password=alumno123

# Dialecto forzado (para evitar el error de conexión)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Configuración de tablas
spring.jpa.hibernate.ddl-auto=none