# --- MICROSERVICIO ACADÉMICO ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-academico
  namespace: tienda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-academico
  template:
    metadata:
      labels:
        app: ms-academico
    spec:
      containers:
      - name: ms-academico
        # CORRECCIÓN: Usamos IMAGE_TAG para que el pipeline lo reemplace automáticamente
        image: 042764456140.dkr.ecr.us-east-1.amazonaws.com/ms-academico:IMAGE_TAG
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef: { name: app-config }
          - secretRef: { name: mysql-secret }
        resources:
          requests: { memory: "256Mi", cpu: "250m" }
          limits: { memory: "512Mi", cpu: "500m" }
# ... [REPETIR EL MISMO CAMBIO DE 'IMAGE_TAG' EN LOS OTROS SERVICIOS]