# --- MICROSERVICIO ACADÉMICO ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-academico
  namespace: tienda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-academico
  template:
    metadata:
      labels:
        app: ms-academico
    spec:
      containers:
      - name: ms-academico
        image: 471112675233.dkr.ecr.us-east-1.amazonaws.com/ms-academico:latest
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef: { name: app-config }
          - secretRef: { name: mysql-secret }
        resources:
          requests: { memory: "256Mi", cpu: "250m" }
          limits: { memory: "512Mi", cpu: "500m" }
---
apiVersion: v1
kind: Service
metadata:
  name: ms-academico
  namespace: tienda
spec:
  selector: { app: ms-academico }
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-academico-hpa
  namespace: tienda
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: ms-academico }
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource: { name: cpu, target: { type: Utilization, averageUtilization: 70 } }
---
# --- MICROSERVICIO ASISTENCIA ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-asistencia
  namespace: tienda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-asistencia
  template:
    metadata:
      labels:
        app: ms-asistencia
    spec:
      containers:
      - name: ms-asistencia
        image: 471112675233.dkr.ecr.us-east-1.amazonaws.com/ms-asistencia:latest
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef: { name: app-config }
          - secretRef: { name: mysql-secret }
        resources:
          requests: { memory: "256Mi", cpu: "250m" }
          limits: { memory: "512Mi", cpu: "500m" }
---
apiVersion: v1
kind: Service
metadata:
  name: ms-asistencia
  namespace: tienda
spec:
  selector: { app: ms-asistencia }
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-asistencia-hpa
  namespace: tienda
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: ms-asistencia }
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource: { name: cpu, target: { type: Utilization, averageUtilization: 70 } }
---
# --- MICROSERVICIO COMUNICACIONES ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-comunicaciones
  namespace: tienda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-comunicaciones
  template:
    metadata:
      labels:
        app: ms-comunicaciones
    spec:
      containers:
      - name: ms-comunicaciones
        image: 471112675233.dkr.ecr.us-east-1.amazonaws.com/ms-comunicaciones:latest
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef: { name: app-config }
          - secretRef: { name: mysql-secret }
        resources:
          requests: { memory: "256Mi", cpu: "250m" }
          limits: { memory: "512Mi", cpu: "500m" }
---
apiVersion: v1
kind: Service
metadata:
  name: ms-comunicaciones
  namespace: tienda
spec:
  selector: { app: ms-comunicaciones }
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-comunicaciones-hpa
  namespace: tienda
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: ms-comunicaciones }
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource: { name: cpu, target: { type: Utilization, averageUtilization: 70 } }

# --- BFF SERVICE ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-service
  namespace: tienda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bff-service
  template:
    metadata:
      labels:
        app: bff-service
    spec:
      containers:
      - name: bff-service
        image: 471112675233.dkr.ecr.us-east-1.amazonaws.com/bff-service:latest
        ports:
        - containerPort: 8080
        env:
        # Aquí configuramos las conexiones internas a los otros servicios
        - name: URL_ACADEMICO
          value: "http://ms-academico:8080/api/estudiantes"
        - name: URL_ASISTENCIA
          value: "http://ms-asistencia:8080/api/asistencia"
        - name: URL_COMUNICACIONES
          value: "http://ms-comunicaciones:8080/api/comunicaciones/resumen"
        resources:
          requests: { memory: "128Mi", cpu: "100m" }
          limits: { memory: "256Mi", cpu: "250m" }
---
apiVersion: v1
kind: Service
metadata:
  name: bff-service
  namespace: tienda
spec:
  selector: { app: bff-service }
  ports:
    - port: 8082
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bff-hpa
  namespace: tienda
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: bff-service }
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource: { name: cpu, target: { type: Utilization, averageUtilization: 70 } }