apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: tienda
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/db_colegio?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  SPRING_DATASOURCE_USERNAME: "root"
  # NOTA: La contraseña NO va aquí, esa se queda en el Secret