apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: tienda
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_DATABASE
          value: "db_colegio"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: db # Este nombre es vital, porque tu backend buscará a 'db'
  namespace: tienda
spec:
  ports:
    - port: 3306
  selector:
    app: db