# 1. Definimos el almacenamiento persistente
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: tienda
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# 2. Deployment de la base de datos con el Secret y el Volumen
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: tienda
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_DATABASE
          value: "db_colegio"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
# 3. Service para que tus servicios encuentren a la DB
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: tienda
spec:
  selector:
    app: db
  ports:
    - port: 3306
      targetPort: 3306