apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: tienda
type: Opaque
stringData:
  # Base64 no es obligatorio si usas stringData, K8s lo convierte solo
  MYSQL_ROOT_PASSWORD: "alumno123"
  SPRING_DATASOURCE_PASSWORD: "alumno123"