name: CI/CD Pipeline a EKS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag y Push de imágenes
        run: |
          SERVICES=("ms-academico" "ms-asistencia" "ms-comunicaciones" "bff-service" "frontend")
          TAG=${{ github.sha }}
          for service in "${SERVICES[@]}"; do
            echo "Construyendo $service con tag $TAG..."
            PATH_TO_BUILD=$([[ "$service" == "frontend" ]] && echo "./frontend" || echo "./$service")
            
            docker build -t $service:$TAG $PATH_TO_BUILD
            docker tag $service:$TAG ${{ secrets.ECR_REGISTRY }}/$service:$TAG
            docker push ${{ secrets.ECR_REGISTRY }}/$service:$TAG
          done

      - name: Ejecutar Snyk para escanear dependencias
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --severity-threshold=high
        continue-on-error: false

      - name: Configurar contexto de EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name nombre-eks

      - name: Desplegar en Kubernetes
        run: |
          TAG=${{ github.sha }}
          # Reemplazamos dinámicamente 'IMAGE_TAG' por el hash del commit actual en tus archivos YAML
          find k8s/ -name "*.yaml" -exec sed -i "s|IMAGE_TAG|$TAG|g" {} +
          
          # Aplicar los despliegues
          kubectl apply -f k8s/
          
          # Reiniciar para aplicar la nueva versión
          kubectl rollout restart deployment/ms-academico -n tienda
          kubectl rollout restart deployment/ms-asistencia -n tienda
          kubectl rollout restart deployment/ms-comunicaciones -n tienda
          kubectl rollout restart deployment/bff-service -n tienda
          kubectl rollout restart deployment/frontend -n tienda