name: CI/CD Pipeline a EKS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag y Push de imágenes
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          SERVICES=("ms-academico" "ms-asistencia" "ms-comunicaciones" "bff-service" "frontend")
          TAG=${{ github.sha }}
          for service in "${SERVICES[@]}"; do
            echo "Construyendo $service con tag $TAG..."
            
            if [[ "$service" == "frontend" ]]; then
              PATH_TO_BUILD="./frontend"
            else
              PATH_TO_BUILD="./backend/$service"
            fi
            
            docker build -t $service:$TAG $PATH_TO_BUILD
            docker tag $service:$TAG $ECR_REGISTRY/$service:$TAG
            docker push $ECR_REGISTRY/$service:$TAG
          done

      - name: Ejecutar Snyk para escanear dependencias
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --severity-threshold=high
        continue-on-error: false

      - name: Configurar contexto de EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name nombre-eks

      - name: Desplegar en Kubernetes
        run: |
          TAG=${{ github.sha }}
          
          # 1. Asegurar el namespace
          kubectl create namespace tienda --dry-run=client -o yaml | kubectl apply -f -
          
          # 2. Reemplazar tags y aplicar archivos
          find k8s/ -name "*.yaml" -exec sed -i "s|IMAGE_TAG|$TAG|g" {} +
          kubectl apply -f k8s/
          
          # 3. Esperar a que el despliegue exista antes de reiniciar
          echo "Esperando 10 segundos para inicializar recursos..."
          sleep 10
          
          # 4. Rollout usando status para verificar que el despliegue sea exitoso
          SERVICES_K8S=("ms-academico" "ms-asistencia" "ms-comunicaciones" "bff-service" "frontend")
          for svc in "${SERVICES_K8S[@]}"; do
            echo "Reiniciando $svc..."
            kubectl rollout restart deployment/$svc -n tienda
            kubectl rollout status deployment/$svc -n tienda --timeout=60s
          done